Studio: Updated ReFramework dependencies for 21.10
UiPath-Services/StudioTemplates pull request #87
Opened 2021-10-08 14:20 UTC by andrei-ungureanu-uipath

2021-10-08 19:11 UTC, aveizu commented
I think we should add Testing Activities dependency: "UiPath.Testing.Activities": "[1.4.2]"

2021-10-11 12:08 UTC, AlvinStanescu requested changes

2021-10-11 12:08 UTC, AlvinStanescu commented on REFramework/contentFiles/any/any/pt1/.local/template.json
>    "DefaultProjectDescription": "NewBusinessProcessProjectDefaultDescription",
The files seem to have changed, e.g. `REFramework/contentFiles/any/any/pt1/CSharp/project.json`

2021-10-11 13:19 UTC, AlvinStanescu approved these changes

2021-10-11 14:00 UTC, lavinianastase approved these changes

2021-10-11 14:01 UTC, merged